feat: build package
linode/apl-k8s-operator-node pull request #5
Opened 2024-11-01 14:03 UTC by ElderMatt

2024-11-04 11:56 UTC, j-zimnowoda requested changes

2024-11-04 11:56 UTC, j-zimnowoda commented on bin/generate-package.sh
> +repo='ssh://git@github.com/linode/apl-k8s-operator-node.git'
this variable is not used

2024-11-04 11:56 UTC, j-zimnowoda commented on bin/common.sh
> +unpublished_exists() {
This function is only used in publish-package.sh, so why not defining it there?

2024-11-27 10:04 UTC, j-zimnowoda requested changes
Package release should not happen on every build.
I recommend to look at build pipelines of other apl related repos.

2025-01-14 09:39 UTC, CasLubbers approved these changes

2025-01-14 09:39 UTC, CasLubbers commented
> Package release should not happen on every build. I recommend to look at build pipelines of other apl related repos.

I've changed it so it publishes only when the build is run from main

2025-01-16 09:09 UTC, merged